export const authActionTypes = {
    CHECK_USER_SESSION: "CHECK_USER_SESSION",

    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE"
}
